model_list:
  - model_name: default
    litellm_params:
      model: openai/default
      api_base: http://127.0.0.1:8000/v1
      api_key: empty
      stream: true
      max_tokens: 32768
      drop_params: True

  - model_name: anthropic/*
    litellm_params:
      model: openai/default
      api_base: http://127.0.0.1:8000/v1
      api_key: empty
      stream: true
      max_tokens: 32768
      drop_params: True